using System.Net.Http.Headers;

namespace API.Tests.Utility;

[TestClass]
public abstract class TestBase
{
    private const string _customerToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yVzVYN2tEMUJiR2RJRGRQR0tJSFNETTBjZnAiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL3N0aXJyaW5nLW11c2tveC0zLmFjY291bnRzLmRldiIsImF6cCI6Imh0dHBzOi8vc3RpcnJpbmctbXVza294LTMuYWNjb3VudHMuZGV2IiwiZXhwIjoyMDEyNzI5MDA4LCJpYXQiOjE2OTczNjkwMDksImlzcyI6Imh0dHBzOi8vc3RpcnJpbmctbXVza294LTMuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiNDk3YTk0NGE4ZmFiN2M0MjRhMTYiLCJuYmYiOjE2OTczNjkwMDQsInJvbGUiOiJjdXN0b21lciIsInN1YiI6InVzZXJfMlduVVJVeFBodUtsUGZpSlFZQ2JvMFR2UkJxIn0.PyzGT5JFC74-uSFBaqQNRXkixWvk9JKg_q3uXLjCPvj3pE1YWZU3JLX4BB9Waad7LRzKWroVUYmS7GoC8C2cQjNYeLyzSYbPk4kmo9DiWEIiQLyuOcQLgfEMvAzJHbHpJoS0jqvu2RaYY3_eyab7k2s5tNr6TlUwyr-5IzWTpFnlFLldlTjrwA4KIK8z81iLhTvHvCtO09pqmfXYL9wrn1_1-AClO9EODyWC4q21oenPd2E1_zzWRt9qfnwhH12pwqqh5wMvhCvsEx1bSMHqI0R5nJ-skSJ2LxRb_akmikTBGiwrtwD6mu48ryW8VUybzYRHEbimFSl4HYapy9qOEw";
    private const string _employeeToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yVzVYN2tEMUJiR2RJRGRQR0tJSFNETTBjZnAiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL3N0aXJyaW5nLW11c2tveC0zLmFjY291bnRzLmRldiIsImF6cCI6Imh0dHBzOi8vc3RpcnJpbmctbXVza294LTMuYWNjb3VudHMuZGV2IiwiZXhwIjoyMDEyNzI4OTgzLCJpYXQiOjE2OTczNjg5ODQsImlzcyI6Imh0dHBzOi8vc3RpcnJpbmctbXVza294LTMuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiYmE5NjEyZDNhYTE2ODIwYmQ1MjkiLCJuYmYiOjE2OTczNjg5NzksInJvbGUiOiJlbXBsb3llZSIsInN1YiI6InVzZXJfMlduVVFGNDRzYlBFQmZmWnBpUlpnek01T2JMIn0.JaVJa8JxP0fYutVgk13_h6rWUyaG685L0sT3DuZ58uFaIlAZ8He0Ns2O8URK9dNqWXmBknCYud6Kw_UL9J_s8cWjtZbTNHHxm_uRYtqhqMHVN4tgfwRELS5Ma8KXruQNtBbi5SwJLaX8n2sgoFsa-C6-9V8qqleSSsqIs65IsuR8bOpmU99oeNreXMNWaeKmQYdYqTE6ElOzESoGRVygibHLM3HblbW4GL0Z_9GTrysQLpsOz9hQszPTbVF8LTQ3YpwONY4lFlOwHsnj1I831NmVlpObVIkNN_ctU8OJrfjAluWy4MgVWmoeCTgVpror7HebjIndhZbFnXSfLSzvKg";
    private const string _adminToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yVzVYN2tEMUJiR2RJRGRQR0tJSFNETTBjZnAiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL3N0aXJyaW5nLW11c2tveC0zLmFjY291bnRzLmRldiIsImF6cCI6Imh0dHBzOi8vc3RpcnJpbmctbXVza294LTMuYWNjb3VudHMuZGV2IiwiZXhwIjoyMDEyNzI4OTYwLCJpYXQiOjE2OTczNjg5NjEsImlzcyI6Imh0dHBzOi8vc3RpcnJpbmctbXVza294LTMuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiZGY5Yjc0MGZiYzM1YmY1OTFkMjUiLCJuYmYiOjE2OTczNjg5NTYsInJvbGUiOiJhZG1pbiIsInN1YiI6InVzZXJfMlduVU9VQ210bk13blpRcHd2QkxuQm5DNnRjIn0.CZhg93B67IywP27egRbWV1iGjZuN3h-CdM5RAtpEH9dIipSXukRLCRFU8eKn8taD69egxZZ7b8NlEx7V2i_saPEcXb8AfRUpanrfiOmbOjtrZ4AWskEOeiixyP6bgdXMXPxkxcp03sayE_fThpABTmjPEe5PicDR8-NwFYXaANUKP5mue8AeKtC9cZ-Tza7GKnDYtgQgj3To7wQXkUQpFh_5djpST4b_nR8Iyfug3NhXiM1rJHrtKPi8lsFIaN3MCyFsrSoPUpB5_HkrujVXl13IaB7DV-zWwL57eChoeezt9ukxnxyG9DtVjVUvDLasssdxRR8ifErlROFTgL6UcQ";
    protected WebApiFactory<Program> _factory;
    protected IServiceProvider _provider;

    [TestInitialize]
    public void Initialize()
    {
        _provider = Startup.ConfigureServices();
        _factory = _provider.GetRequiredService<WebApiFactory<Program>>();
    }

    protected HttpClient CreateClient(string token = null)
    {
        var client = _factory.CreateClient();
        if (!string.IsNullOrEmpty(token))
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

        return client;
    }

    protected HttpClient CreateAdminClient() => CreateClient(_adminToken);
    protected HttpClient CreateEmployeeClient() => CreateClient(_employeeToken);
    protected HttpClient CreateCustomerClient() => CreateClient(_customerToken);
}
